model:
  base_learning_rate: 4.5e-6
  target: dlformer.models.vqgan_vi_coco.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    ckpt_path: /home/ubuntu/Workspace/abc/dlformer_demo_pkg/dlformer_demo/data/coco_models.ckpt
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 240
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4] # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [15]
      dropout: 0.0
    lossconfig:
      target: dlformer.modules.losses.vqperceptual_vi.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 100
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: utils.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: dlformer.data.custom_vi_trans_sudomask.CustomTrain
      params:
        training_images_list_file: data/39ffa3a4a4.txt
        training_mask_file: data/39ffa3a4a4_mask.txt
        h: 240
        w: 432
    validation:
      target: dlformer.data.custom_vi_trans_sudomask.CustomTest
      params:
        test_images_list_file: data/39ffa3a4a4.txt
        test_mask_file: data/39ffa3a4a4_mask.txt
        h: 240
        w: 432
